language: c++

branches:
  except:
    - automatic

cache:
  directories:
    - download

matrix:
  include:

    # Windows 32 bits
    - os: linux
      sudo: required
      dist: trusty
      env:
        - _BUILD=win32
        - _MINGW=mingw32
        - _HOST=i686-w64-mingw32
      before_install:
        - sudo add-apt-repository ppa:kxstudio-debian/kxstudio -y
        - sudo add-apt-repository ppa:kxstudio-debian/mingw -y
        - sudo add-apt-repository ppa:kxstudio-debian/toolchain -y
        - sudo apt-get update -qq
        - sudo apt-get install kxstudio-repos
        - sudo apt-get update -qq
      install:
        - >
          sudo apt-get install -y
          g++
          pkg-config
          "${_MINGW}"-x-gcc
          "${_MINGW}"-x-pkgconfig
          wine
      script:
        - bash .travis/script-mingw.sh
        - cp -drfv bin ninjas2-"$_BUILD"
        - rm -f ninjas2-"$_BUILD"/README
        - install -d release
        - zip -9 -r release/ninjas2-"$_BUILD".zip ninjas2-"$_BUILD"

    # Windows 64 bits
    - os: linux
      sudo: required
      dist: trusty
      env:
        - _BUILD=win64
        - _MINGW=mingw64
        - _HOST=x86_64-w64-mingw32
      before_install:
        - sudo add-apt-repository ppa:kxstudio-debian/kxstudio -y
        - sudo add-apt-repository ppa:kxstudio-debian/mingw -y
        - sudo add-apt-repository ppa:kxstudio-debian/toolchain -y
        - sudo apt-get update -qq
        - sudo apt-get install kxstudio-repos
        - sudo apt-get update -qq
      install:
        - >
          sudo apt-get install -y
          g++
          pkg-config
          "${_MINGW}"-x-gcc
          "${_MINGW}"-x-pkgconfig
          wine
      script:
        - bash .travis/script-mingw.sh
        - cp -drfv bin ninjas2-"$_BUILD"
        - rm -f ninjas2-"$_BUILD"/README
        - install -d release
        - zip -9 -r release/ninjas2-"$_BUILD".zip ninjas2-"$_BUILD"

    # macOS
    - os: osx
      sudo: required
      env:
        - _BUILD=macos
      script:
        - bash .travis/script-macos.sh
        - cp -av bin ninjas2-"$_BUILD"
        - rm -f ninjas2-"$_BUILD"/README
        - install -d release
        - zip -9 -r release/ninjas2-"$_BUILD".zip ninjas2-"$_BUILD"

before_deploy:
  - >
    if test "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false"; then
      export TRAVIS_TAG=automatic
      git tag -f "$TRAVIS_TAG"
    fi

deploy:
  provider: releases
  api_key: e0a624a312b88ec8b9ab2ef7633827239ba50aa3
  file: release/*
  file_glob: true
  skip_cleanup: true
  prerelease: true
  #draft: true
  overwrite: true
  on:
    branch: master

# TODO: replace me $GITHUB_TOKEN (a personal access token with repo rights)
#  travis login --com
#  travis encrypt GITHUB_TOKEN=<the-token-value> --com --add
env:
  global:
    secure: aavJSLnvxBe8U3JuJFXnG0xsllyULSngiX9F4HnvwsPHP4JSMsKEdgOjHrnKogYnk7U5jzWFvMxma3Xg5SJoWQhOxvrLiRFfXIwxVUblF1j+ycgUWr+xrin5kZQBRGrb4A3citqdFnUjuCKTfU2is44MLuhBGWSQ+B76VYH1wK5lgZdZ+KeWHIQvnCMDSfm551jYah+qq851EtNnEyvYoy+9/ABo9thFNz1uoIsjhd5HUyV5eVezHFS+Rb2BjrOXts2jD0/UjyO81QhGJIrd9hF1IbcVs6XAczldFCLOjF+bsbanaFURt7unFjnjTuwADujuxZLiWK5VeOzUE/9Xo1awhUvKuW61AuiThiWH2/ET7VYFkQU3JYm4h19Q/X22sXCST5wLTkOcGgYooKOj4Orx6AAg2NzmRfwQrgUziYMXhSiZMCjzY8vm4eCCC/9MQXreU05LF9pR6oh7ZuwLEjM+XeMC+UH5VdAge/u+cGVKV7AQXD54N+WwLVxTk1YPd5P27rGYXhrWgvEytULnW6CdELHiCzWJ3c4LORS3aoBffGewJFKhhcXFoVisv+KWcu5OFvVJceHFdgiYyDsr9zgMDF/oSgEltZYlAXJ5dJ7t4l3RMkaFziZJAo1MT+0w50ruRbL6d1ixeEyu1nR9WicJzF2huyXho+h1+s7NhqQ=

